#!/usr/bin/env node
// build.js — generates js/data.js from metadata.yaml
// Run: node build.js

import { readFileSync, writeFileSync } from 'fs';
import { load } from 'js-yaml';

const yaml = readFileSync('metadata.yaml', 'utf8');
const meta = load(yaml);

// Map YAML keys to site medium keys and image folder names
const mediumConfig = {
  paintings: {
    key: 'paintings',
    folder: 'paintings',
  },
  works_on_paper: {
    key: 'works-on-paper',
    folder: 'works-on-paper',
  },
  sculpture: {
    key: 'sculpture',
    folder: 'sculpture',
  },
};

function buildMedium(yamlKey, works) {
  const { key, folder } = mediumConfig[yamlKey];
  if (!works || works.length === 0) return `  '${key}': []`;

  const entries = works.map((w, i) => {
    const id = `${yamlKey[0]}${i + 1}`;
    const year = w.year != null ? w.year : 'null';
    const dims = (w.dimensions || '').replace(/'/g, "\\'");
    const medium = (w.medium || '').replace(/'/g, "\\'");
    const title = (w.title || '').replace(/'/g, "\\'");
    return [
      `    { id: '${id}', slug: '${w.slug}', title: '${title}',`,
      `      year: ${year}, medium: '${key}', dims: '${dims}',`,
      `      materials: '${medium}',`,
      `      img:   'images/${folder}/web/${w.slug}.jpg',`,
      `      thumb: 'images/${folder}/thumbs/${w.slug}.jpg' }`,
    ].join('\n');
  });

  return `  '${key}': [\n${entries.join(',\n')}\n  ]`;
}

const sections = Object.entries(meta)
  .filter(([k]) => mediumConfig[k])
  .map(([k, v]) => buildMedium(k, v))
  .join(',\n');

const output = `// AUTO-GENERATED by build.js — do not edit by hand.
// Edit metadata.yaml instead, then run: node build.js

const artworks = {
${sections}
};
`;

writeFileSync('js/data.js', output);
console.log('Built js/data.js from metadata.yaml');
